# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_4au_f4ikwn/clone/recipe, last modified Thu Dec  1 18:40:03 2022
# ------------------------------------------------

package:
  name: xz
  version: 5.2.8
source:
  sha256: 1f8a43d9fcf325d049a31fe4514dc8c44a6d00ce8860d48c4212d1e349d2a3ed
  url: https://downloads.sourceforge.net/project/lzmautils/xz-5.2.8.tar.bz2
build:
  number: '0'
  run_exports:
    - xz >=5.2.8,<6.0a0
  string: h80987f9_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - automake 1.16.5 pl5340hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 hc377ac9_1008
    - llvm-tools 14.0.6 h7ec7a93_1
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.3 h1a28f6b_3
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1a28f6b_2
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host: []
  run: []
test:
  commands:
    - xz --help
    - unxz --help
    - lzma --help
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME
  requires:
    - conda-build
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: https://git.tukaani.org/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  doc_url: https://tukaani.org/xz/
  home: https://tukaani.org/xz/
  license: LGPL-2.1-or-later and GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4abfd0d6-1335-4a09-bd9f-7696b0617785
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/xz-feedstock.git
  sha: baec3a8c687512da4caf3f8bdffee3cd99979cb2
